[package]
name = "chrono_machines_native"
version = "0.1.0"
edition = "2024"
authors = ["Abdelkader Boudih <terminale@gmail.com>"]
license = "MIT"
description = "Ruby FFI binding for chrono_machines"
repository = "https://github.com/seuros/chrono_machines"

[lib]
name = "chrono_machines_native"
crate-type = ["cdylib"]

[dependencies]
chrono-machines = { workspace = true, features = ["std"] }
magnus = { version = "0.8", features = ["embed"] }
rand = { workspace = true }

[features]
default = ["std"]
std = ["chrono-machines/std"]
